(function(){
/* 家庭点菜 · 本机交互原型。所有服务行为均为显式模拟。 */
'use strict';
const D=MealDomain, KEY='family-meal.prototype.2', $=s=>document.querySelector(s);
const icons={home:'<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>',catalog:'<path d="M5 3v6c0 3 4 3 4 0V3M7 3v18M17 3c-3 5-3 8 0 8h2V3zM19 11v10"/>',history:'<path d="M3 11a9 9 0 1 1 2 7M3 5v6h6M12 7v5l3 2"/>',profile:'<circle cx="12" cy="8" r="4"/><path d="M4 21c0-6 16-6 16 0"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',check:'<path d="m5 12 5 5L20 6"/>',arrow:'<path d="m9 5 7 7-7 7"/>',book:'<path d="M4 4h7a3 3 0 0 1 3 3v14a4 4 0 0 0-3-2H4zM20 4h-3a3 3 0 0 0-3 3M20 4v15h-3"/>'};
const icon=(n,c='')=>`<svg class="icon ${c}" viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.book}</svg>`;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel=d=>{const a=d.split('-');return `${Number(a[1])} 月 ${Number(a[2])} 日`;};
const statusName={pending:'待做',cooking:'正在做',completed:'已完成',cancelled:'已取消'};
let state=D.seed(),ui=defaultUI(),lastFocused=null,modalCallback=null,fileURL=null;
function defaultUI(){return {member:null,page:'identity',param:null,stack:[],drafts:{},pending:{},search:'',category:'all',menuFilter:'all',scene:'normal',offline:false,nextUnknown:false,nextConflict:false,nextVersion:false,loading:false,edit:null,dirty:false,review:null,voteForm:null,repeat:[],address:'http://192.168.1.100:8080'};}
try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.state?.version===2){state=x.state;ui={...defaultUI(),...x.ui};}}catch(_){}
function save(required=false){try{localStorage.setItem(KEY,JSON.stringify({state,ui}));return true;}catch(e){if(required){toast('本机存储不可用，尚未发送。请允许浏览器保存数据后重试。');return false;}return false;}}
const actor=()=>state.members.find(m=>m.id===ui.member);
const scope=()=>`${state.instance}|${state.epoch}|${ui.member}`;
const draft=()=>ui.drafts[scope()]||(ui.drafts[scope()]=[]);
const pending=()=>ui.pending[scope()]||null;
const dish=id=>state.dishes.find(d=>d.id===id);
const menuItem=id=>state.items.find(i=>i.id===id);
const dailyReviews=i=>state.reviews.filter(r=>r.dishId===i.dishId&&r.date===i.date);
const currentVote=()=>state.votes.find(v=>v.status==='active');
const latestResult=()=>[...state.votes].reverse().find(v=>v.status!=='active');
const initials=m=>m?.name?.slice(0,1)||'家';
const avatar=(m,large=false)=>`<span class="avatar ${esc(m?.id)} ${large?'large':''}">${esc(initials(m))}</span>`;
function food(d,large=false){return `<div class="food ${esc(d?.tone||'rice')} ${large?'large':''}" aria-label="菜品示意封面">${large?'<span>示意封面</span>':''}</div>`;}
const btn=(label,action,cls='primary',data='',disabled=false)=>`<button type="button" class="${cls}" data-action="${action}" ${data} ${disabled?'disabled':''}>${label}</button>`;
const pagebar=title=>`<div class="pagebar">${btn('‹','back','back','aria-label="返回"')}<h2>${esc(title)}</h2><span class="spacer"></span></div>`;
const empty=(title,desc,action,label)=>`<div class="empty"><div class="empty-mark">${icon('book')}</div><h3>${esc(title)}</h3><p>${esc(desc)}</p>${action?btn(label,action):''}</div>`;
const top=()=>`<div class="topline"><span><span class="eyebrow">FAMILY TABLE</span><br><small class="muted">${esc(state.family?.name||'家庭点菜')} · ${dateLabel(state.today)}</small></span>${btn(avatar(actor())+esc(actor()?.name||'选择成员'),'identity','member-chip')}</div>`;
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3100);}
function modal(title,content,buttons=[]){const d=$('#modal');lastFocused=document.activeElement;d.innerHTML=`<h2>${esc(title)}</h2>${content}<div class="actions">${buttons.join('')}${btn('返回','closeModal','secondary')}</div>`;if(!d.open)d.showModal();}
function closeModal(){const d=$('#modal');if(d.open)d.close();modalCallback=null;if(lastFocused?.isConnected)lastFocused.focus();}
function confirmAction(title,description,fn,label='确认',danger=false){modalCallback=fn;modal(title,`<p>${esc(description)}</p>`,[btn(label,'confirmModal',danger?'danger':'primary')]);}
function rawGo(page,param=null,push=true){if(push&&ui.page!==page)ui.stack.push({page:ui.page,param:ui.param});ui.page=page;ui.param=param;ui.dirty=false;
 if(page==='dishForm'){const d=param?dish(param):null;ui.edit=d?D.clone(d):{id:null,name:'',categoryId:state.categories.find(c=>c.active)?.id||'',minutes:'',intro:'',steps:[],revision:1,cover:null};}
 if(page==='review')ui.review={id:param,rating:0,comment:''};
 if(page==='voteForm')ui.voteForm={title:'今晚吃什么？',dishIds:[]};
 if(page==='repeat')ui.repeat=[];save();render(true);}
function go(page,param=null,push=true){if(ui.dirty){confirmAction('离开编辑？','未保存的内容会被放弃。',()=>rawGo(page,param,push),'放弃并离开',true);return;}rawGo(page,param,push);}
function back(){if(!ui.stack.length){go(ui.member?'home':'identity',null,false);return;}const p=ui.stack[ui.stack.length-1];const run=()=>{ui.stack.pop();rawGo(p.page,p.param,false);};if(ui.dirty)confirmAction('离开编辑？','未保存的内容会被放弃。',run,'放弃并离开',true);else run();}
function run(action,p={},opts={}){if(ui.offline){toast('当前处于离线演示，内容已保留。请恢复连接后操作。');return null;}try{const res=D.execute(state,opts.actor||ui.member,action,p);state=res.state;save();return res.result??true;}catch(e){showError(e);return null;}}
function showError(e){if(e.code==='MEMBER_IN_USE'){const d=e.details;modal('请先处理相关事项',`<p>${esc(e.message)}</p><div class="stack mt">${[...(d.pending||[]),...(d.cooking||[])].map(i=>btn(`${esc(i.name)} · ${dateLabel(i.date)} · ${statusName[i.status]}`,'dependencyItem','secondary',`data-id="${i.id}"`)).join('')}${(d.votes||[]).map(v=>btn(esc(v.title),'dependencyVote','secondary',`data-id="${v.id}"`)).join('')}</div>`);return;}
 if(e.code==='VERSION_CONFLICT'){modal('资料已有新的内容',`<p>其他成员已经保存。你的输入仍保留，请先查看当前资料，再重新编辑；不会自动覆盖。</p>`,[btn('查看当前资料','inspectLatest','primary',`data-id="${esc(ui.edit?.id||ui.param)}"`)]);return;}
 if(e.code==='DATA_EPOCH_CHANGED'){modal('家庭数据已重新载入','<p>旧提交不会自动重送。请核对现有菜单，再重新选择需要的菜。</p>',[btn('核对菜单','menu','primary',`data-date="${state.today}"`)]);return;}
 toast(e.message||'暂时无法完成，请重试');}
function addDish(id,sourceItem=null,note=''){if(!D.available(state,id)){toast('这道菜目前不可点');return;}if(pending()){go('draft');toast('请先确认上一次提交结果');return;}if(draft().length>=50){toast('一次最多选择 50 条菜品');return;}draft().push({localId:'draft-'+Date.now()+'-'+Math.random().toString(16).slice(2),dishId:id,note,sourceItem});save();render();toast(`${dish(id).name}已加入已选菜品`);}
function headerBanner(){const unknown=pending();return `${ui.offline?'<div class="banner error mb"><span>当前离线 · 已保留本机内容</span>'+btn('恢复','online','mini')+'</div>':''}${unknown&&ui.page!=='draft'?btn('<span><b>提交结果尚未确认</b><small>核对后再继续点菜</small></span>›','draft','banner info'):''}`;}
function menuCard(i){const r=dailyReviews(i),mine=r.some(r=>r.memberId===ui.member),mean=r.length?(r.reduce((s,x)=>s+x.rating,0)/r.length).toFixed(1):null;return `<div class="card dish-row"><button class="row-open" data-action="item" data-id="${i.id}">${food(i)}<span class="dish-info"><b>${esc(i.name)}</b><small>${esc(i.orderedName)}点的${i.cookName?' · '+esc(i.cookName)+'做':''}${i.date!==state.today?' · '+dateLabel(i.date):''}</small>${i.note?`<small>${esc(i.note)}</small>`:''}${mean?`<small>★ ${mean} · ${r.length} 条当日评价</small>`:''}</span></button><div class="status-side"><span class="badge ${i.status}">${statusName[i.status]}</span>${i.status==='pending'?btn('我要做','claim','mini',`data-id="${i.id}"`):i.status==='cooking'&&i.cook===ui.member?btn('继续做','item','mini',`data-id="${i.id}"`):i.status==='completed'&&!mine?btn('去评价','review','mini',`data-id="${i.id}"`):''}</div></div>`;}
function home(){const items=state.items.filter(i=>i.date===state.today),valid=items.filter(i=>i.status!=='cancelled'),done=items.filter(i=>i.status==='completed'),overdue=state.items.filter(i=>i.date<state.today&&['pending','cooking'].includes(i.status)),v=currentVote(),latest=latestResult();return `${top()}<h1>今天，想吃点什么？</h1><p class="subtitle">一起点菜，把家常饭安排好。</p><div class="hero"><div class="hero-head"><div><small>今日菜单</small><div class="mt"><strong>${valid.length}</strong> <span class="small muted">道菜，等大家一起吃</span></div></div>${icon('catalog')}</div><div class="progress"><i style="width:${valid.length?done.length/valid.length*100:0}%"></i></div><div class="stats">${['pending','cooking','completed'].map(t=>`<button data-action="menu" data-date="${state.today}" data-filter="${t}"><b>${items.filter(i=>i.status===t).length}</b><span>${statusName[t]}</span></button>`).join('')}</div></div>${overdue.length?btn(`<span><b>往日还有 ${overdue.length} 道菜未完成</b><small>保留原日期，可以接着做或取消</small></span>›`,'overdue','banner'):''}<div class="section-head"><h2>今天的菜</h2>${btn('查看全部 ›','menu','text-button',`data-date="${state.today}"`)}</div><div class="stack">${items.slice(0,4).map(menuCard).join('')||empty('今天还没有点菜','到菜品库选几道，大家一起做。','catalog','去点菜')}</div><div class="section-head"><h2>今晚吃什么</h2>${!v?btn('发起投票','voteForm','text-button'):''}</div>${v?`<button class="card row between" style="width:100%;text-align:left" data-action="vote" data-id="${v.id}"><div><span class="badge pending">投票中</span><h3 class="tight">${esc(v.title)}</h3><p class="subtitle">${Object.keys(v.ballots).length} 人已投 · ${v.candidates.length} 道候选</p></div><span>›</span></button>`:!latest?`<div class="card"><h3>难以决定？让家人选一选</h3><p class="subtitle">选几道候选菜，发起一轮轻量投票。</p></div>`:''}${latest?btn(`<span><b>最近一轮 · ${esc(latest.title)}</b><small>${latest.status==='cancelled'?'已取消，没有获胜菜':esc(latest.candidates.find(c=>c.dishId===latest.winner)?.name)+' · 查看结果'}</small></span>›`,'vote','banner info',`data-id="${latest.id}"`):''}`;}
function catalog(){let list=state.dishes.filter(d=>D.available(state,d.id)&&(ui.category==='all'||d.categoryId===ui.category)&&D.norm(d.name).includes(D.norm(ui.search)));return `${top()}<h1>家里的拿手菜</h1><p class="subtitle">想吃哪一道，就加到已选菜品里。</p><label class="search">${icon('search')}<input id="search" aria-label="搜索菜品" placeholder="搜索菜名" value="${esc(ui.search)}"></label><div class="pill-row">${[{id:'all',name:'全部'},...state.categories.filter(c=>c.active)].map(c=>btn(esc(c.name),'filterCategory','pill '+(ui.category===c.id?'active':''),`data-id="${c.id}"`)).join('')}</div><div class="stack">${list.map(d=>{const a=D.average(state,d.id),n=draft().filter(x=>x.dishId===d.id).length;return `<div class="card dish-row"><button class="row-open" data-action="dish" data-id="${d.id}">${food(d)}<span class="dish-info"><b>${esc(d.name)}</b><small>${esc(state.categories.find(c=>c.id===d.categoryId)?.name)}${d.minutes?' · '+d.minutes+' 分钟':''}</small><small>${a.value?'★ '+a.value.toFixed(1)+' · '+a.count+' 条评价':'还没有评价'}${n?' · 已选 '+n+' 份':''}</small></span></button>${btn('+','addDish','add',`data-id="${d.id}" aria-label="添加${esc(d.name)}"`)}</div>`;}).join('')||empty('没有找到合适的菜','可以换个关键词，或去公共菜品管理新建一道菜。','manage','管理菜品')}</div>${draft().length?btn(`<span><b>已选 ${draft().length} 道</b><small>${esc(actor()?.name)}的本机草稿</small></span><strong>去确认 →</strong>`,'draft','checkout'):''}`;}
function draftView(){const p=pending(),items=draft();return `${pagebar('已选菜品')}<p class="subtitle mb">本次由 <b>${esc(actor()?.name)}</b> 点菜 · ${dateLabel(p?.date||state.today)}</p>${p?'<div class="banner info mb"><span><b>提交结果尚未确认</b><small>原内容已锁定。刷新页面也不会重复点菜。</small></span></div>':''}<div class="stack">${items.map((x,k)=>{const d=dish(x.dishId);return `<div class="card"><div class="row">${food(d)}<div class="grow"><h3>${esc(d?.name||'不可用菜品')}</h3><small class="muted">第 ${k+1} 条 · ${D.available(state,x.dishId)?'独立备注':'目前不可点'}</small></div>${btn('移除','removeDraft','text-button',`data-id="${x.localId}"`,!!p)}</div><textarea class="note-input" data-draft="${x.localId}" maxlength="200" aria-label="第${k+1}条备注" placeholder="这道菜有什么特别要求？" ${p?'disabled':''}>${esc(x.note)}</textarea></div>`;}).join('')||empty('还没有选择菜品','加号只加入本机草稿，确认提交后家人才会看到。','catalog','去点菜')}</div>${items.length?`<div class="actions">${btn(p?'确认提交结果':ui.submitting?'正在提交…':`提交 ${items.length} 道菜`,p?'reconcile':'submit','primary','',!!ui.submitting)}${!p?'<p class="small muted">同一道菜多次添加，会保留为不同的点菜事项。</p>':'<p class="small muted">核对同一个请求凭据，不会创建第二批。</p>'}</div>`:''}`;}
function dishView(id){const d=dish(id);if(!d)return empty('菜品不存在','请返回菜品库重新查看。','catalog','返回菜品库');const a=D.average(state,id),rs=state.reviews.filter(r=>state.items.some(i=>i.id===r.itemId&&i.dishId===id));return `${pagebar('菜品详情')}${food(d,true)}<div class="row between"><h1 style="font-size:26px">${esc(d.name)}</h1><span class="badge ${d.active?'pending':'cancelled'}">${d.active?'上架':'下架'}</span></div><p class="subtitle">${esc(state.categories.find(c=>c.id===d.categoryId)?.name)}${d.minutes?' · 约 '+d.minutes+' 分钟':''} · ${a.value?'★ '+a.value.toFixed(1):'未评价'}</p><p class="mt small muted">${esc(d.intro)||'暂无简介'}</p>${d.cover?`<div class="note">原文件：${esc(d.cover.name)} · ${(d.cover.size/1048576).toFixed(2)} MiB<br>本原型仅保存文件元信息；原文件取回功能属于正式服务验收范围。</div>`:''}<div class="section-head"><h2>怎么做</h2>${btn('编辑资料','dishForm','text-button',`data-id="${id}"`)}</div><div class="card">${recipe(d)}</div><p class="small muted mt">当前菜谱 · ${esc(d.updatedAt?.slice(0,10)||state.today)} 更新</p><div class="section-head"><h2>家人的评价</h2><span class="small muted">${rs.length} 条</span></div><div class="stack">${rs.map(reviewCard).join('')||empty('还没有评价','完成一次做菜后，家人就能评价。')}</div><div class="actions">${btn(d.active?'加入已选菜品':'这道菜目前不可点','addDish','primary',`data-id="${d.id}"`,!D.available(state,id))}</div>`;}
function recipe(d){return d?.steps?.length?d.steps.map((s,i)=>`<div class="step"><span class="step-number">${i+1}</span><p>${esc(s)}</p></div>`).join(''):'<p class="small muted">还没有记录做法。所有启用成员都可以补充这道公共菜的资料。</p>';}
function menu(date){const archive=date<state.today,all=state.items.filter(i=>i.date===date&&(!archive||['completed','cancelled'].includes(i.status))),filters=archive?['all','completed','cancelled']:['all','pending','cooking','completed','cancelled'],items=all.filter(i=>ui.menuFilter==='all'||i.status===ui.menuFilter);return `${pagebar(date===state.today?'今日菜单':dateLabel(date)+' · 已归档')}<p class="subtitle">${esc(date)} · ${archive?'已自动归档的完成与取消事项':'按点菜日期保留记录'}</p><div class="pill-row">${filters.map(s=>btn((s==='all'?'全部':statusName[s])+' '+all.filter(i=>s==='all'||i.status===s).length,'menuFilter','pill '+(ui.menuFilter===s?'active':''),`data-status="${s}"`)).join('')}</div><div class="stack">${items.map(menuCard).join('')||empty('这里还没有事项',archive?'往日未完成会继续留在独立入口。':'可以查看其他状态，或到菜品库选菜。')}</div>${archive&&all.length?`<div class="actions">${btn('选择菜品，再来一次','repeat','primary',`data-date="${date}"`)}</div>`:''}`;}
function itemView(id){const i=menuItem(id);if(!i)return empty('事项不存在','请返回菜单重新查看。','home','返回首页');const d=dish(i.dishId),ownCook=i.cook===ui.member,ownOrder=i.orderedBy===ui.member,rs=dailyReviews(i),mine=rs.find(r=>r.memberId===ui.member);return `${pagebar('做菜与点菜记录')}<div class="row between mb"><span class="badge ${i.status}">${statusName[i.status]}</span><small class="muted">${esc(i.date)}</small></div><h1 style="font-size:27px">${esc(i.name)}</h1><dl class="meta-grid"><dt>点菜人</dt><dd>${esc(i.orderedName)}</dd><dt>做菜人</dt><dd>${esc(i.cookName||'等待认领')}</dd><dt>本次备注</dt><dd>${esc(i.note||'没有特别要求')}</dd>${i.status==='cancelled'?`<dt>取消人</dt><dd>${esc(D.memberName(state,i.cancelledBy))}</dd><dt>取消说明</dt><dd>${esc(i.cancelReason||'未填写原因')}</dd>`:''}</dl>${i.date<state.today?'<div class="note">这是往日的事项。继续处理不会改变原来的菜单日期。</div>':''}<div class="section-head"><h2>当前做法</h2>${btn('菜品资料 ›','dish','text-button',`data-id="${i.dishId}"`)}</div><div class="card">${recipe(d)}</div><p class="small muted mt">菜名与封面使用本次点菜快照；做法来自当前菜谱。</p><div class="actions">${i.status==='pending'?btn('我要做','claim','primary',`data-id="${id}"`):''}${i.status==='pending'&&ownOrder?btn('编辑本次备注','editNote','secondary',`data-id="${id}"`)+btn('取消这次点菜','cancelItem','danger',`data-id="${id}"`):''}${i.status==='cooking'&&ownCook?btn('做好了','complete','primary',`data-id="${id}"`)+`<div class="split-actions">${btn('取消认领','unclaim','secondary',`data-id="${id}"`)}${btn('不做了','cancelItem','danger',`data-id="${id}"`)}</div>`:''}${i.status==='cooking'&&!ownCook?'<div class="note">'+esc(i.cookName)+' 正在做。当前成员只能查看。</div>':''}${i.status==='completed'&&!mine?btn('评价这道菜','review','primary',`data-id="${id}"`):''}${i.status==='completed'&&mine?`<div class="note">你已提交这道菜在 ${esc(i.date)} 的评价；提交后不能修改。</div>`:''}${i.status==='cancelled'?btn('另行点一次','addDish','secondary',`data-id="${i.dishId}"`,!D.available(state,i.dishId)):''}</div>${i.status==='completed'?`<div class="section-head"><h2>${esc(i.date)} 的当日评价</h2></div><div class="stack">${rs.map(reviewCard).join('')||empty('还没有评价','每位成员对同一道菜每天可以评价一次，提交后不能修改。')}</div>`:''}`;}
function reviewCard(r){return `<div class="card review-card"><div class="row between"><b class="small">${esc(r.memberName)}</b><span class="rating">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</span></div><p>${esc(r.comment||'只留下了评分')}</p></div>`;}
function reviewView(){const r=ui.review,i=menuItem(r?.id);if(!i)return empty('事项不存在','请从已完成事项进入。');const existing=dailyReviews(i).find(x=>x.memberId===ui.member);if(existing)return `${pagebar('当日评价')}<div class="card row">${food(i)}<div><h3>${esc(i.name)}</h3><p class="small muted">${dateLabel(i.date)}</p></div></div><p class="note">当天已经评价过这道菜。评价提交后不能修改；下一个业务日期完成这道菜后可以再次评价。</p>${reviewCard(existing)}`;return `${pagebar('评价这道菜')}<div class="card row">${food(i)}<div><h3>${esc(i.name)}</h3><p class="small muted">${esc(i.cookName)}做的 · ${dateLabel(i.date)}</p></div></div><p class="subtitle mt">这道菜，合不合口味？</p><div class="stars" role="group" aria-label="评分">${[1,2,3,4,5].map(n=>btn('★','rate',n<=r.rating?'on':'',`data-rating="${n}" aria-label="${n}星"`)).join('')}</div><p class="small muted" style="text-align:center">${r.rating?r.rating+' 星':'请选择 1—5 星'}</p><label class="field"><span>想说的话（选填）</span><textarea id="reviewComment" rows="4" maxlength="1000" placeholder="例如：咸淡刚好，下次还想吃。">${esc(r.comment)}</textarea></label>${btn('提交评价','saveReview','primary','',!r.rating)}<p class="note">同一成员对同一道菜每天只能评价一次，提交后不能修改。</p>`;}
function historyView(){const dates=[...new Set(state.items.filter(i=>i.date<state.today&&['completed','cancelled'].includes(i.status)).map(i=>i.date))].sort().reverse();return `${top()}<h1>吃过的家常味</h1><p class="subtitle mb">日期结束后，完成或取消的事项会自动按原日期归档。</p><div class="stack mt">${dates.map(date=>{const xs=state.items.filter(i=>i.date===date&&['completed','cancelled'].includes(i.status)),a=D.dayAverage(state,date);return `<button class="card" data-action="menu" data-date="${date}" style="text-align:left"><div class="row between"><h3>${dateLabel(date)}</h3><span class="muted">›</span></div><p class="subtitle">${xs.map(i=>esc(i.name)).join('、')}</p><div class="row between mt"><small class="muted">${xs.filter(i=>i.status==='completed').length} 道完成 · ${xs.filter(i=>i.status==='cancelled').length} 道取消</small><small class="muted">${a?'★ '+a.toFixed(1):'未评价'}</small></div></button>`;}).join('')||empty('还没有归档记录','往日未完成会继续留在首页独立入口。')}</div>`;}
function repeatView(date){const xs=state.items.filter(i=>i.date===date&&['completed','cancelled'].includes(i.status));return `${pagebar('再来一次')}<p class="subtitle mb">选中的菜会进入 ${esc(actor()?.name)} 的已选列表，默认保留原备注。</p>${xs.map(i=>{const valid=D.available(state,i.dishId);return `<label class="checkbox-row ${!valid?'disabled':''}"><input type="checkbox" data-repeat="${i.id}" ${ui.repeat.includes(i.id)?'checked':''} ${valid?'':'disabled'}><span class="grow"><b>${esc(i.name)}</b><small>${valid?esc(i.note||'没有特别备注'):'目前已下架或分类停用，不能复点'}</small></span></label>`;}).join('')}<div class="actions">${btn(`加入已选（${ui.repeat.length}）`,'repeatAdd','primary','',!ui.repeat.length)}</div>`;}
function voteView(id){
 const v=state.votes.find(x=>x.id===id)||currentVote()||latestResult();
 if(!v)return `${pagebar('今晚吃什么')}${empty('还没有投票','先选 2—10 道候选菜，让家人一起决定。','voteForm','发起投票')}`;
 const c=D.counts(v),total=Object.keys(v.ballots).length,owner=v.initiator===ui.member,added=state.items.find(i=>i.sourceVote===v.id),mine=v.ballots[ui.member]||[];
 return `${pagebar(v.status==='active'?'今晚吃什么':'最近一轮结果')}<span class="badge ${v.status==='active'?'pending':v.status==='finished'?'completed':'cancelled'}">${v.status==='active'?'进行中':v.status==='finished'?'已结束':'已取消'}</span><h1 class="mt" style="font-size:26px">${esc(v.title)}</h1><p class="subtitle mb">${esc(v.initiatorName)}发起 · ${total} 人已投票</p>${v.status==='finished'?`<div class="hero mb"><small>这一次，大家选了</small><h2 class="mt">${esc(v.candidates.find(x=>x.dishId===v.winner)?.name)}</h2><p class="subtitle">${c[v.winner]} 票${D.leaders(v).length>1?' · 由发起人在并列候选中选定':''}</p></div>`:''}${v.candidates.map(x=>`<div class="vote-card ${mine.includes(x.dishId)?'selected':''}"><div class="row">${food(x)}<div class="grow"><h3>${esc(x.name)}</h3><small class="muted">${mine.includes(x.dishId)?'我的选择':v.winner===x.dishId?'本轮获胜':''}</small></div><b>${c[x.dishId]} <small class="muted">票</small></b></div><div class="vote-bar"><i style="width:${total?c[x.dishId]/total*100:0}%"></i></div>${v.status==='active'?btn(mine.includes(x.dishId)?'取消选择':'选择这道菜','ballot','secondary',`data-id="${v.id}" data-dish="${x.dishId}"`):''}</div>`).join('')}<div class="actions">${v.status==='active'?'<p class="note">每位成员可以选择一道或多道候选菜，也可以在结束前取消或增选。</p>':''}${v.status==='active'&&owner?btn('结束投票','finishVote','primary',`data-id="${v.id}"`)+btn('取消本轮投票','cancelVote','danger',`data-id="${v.id}"`):''}${v.status==='finished'?(added?btn(`已加入 ${dateLabel(added.date)} · ${statusName[added.status]}　›`,'item','secondary',`data-id="${added.id}"`):btn(D.available(state,v.winner)?'将获胜菜加入今日菜单':'获胜菜目前不可点','addWinner','primary',`data-id="${v.id}"`,!D.available(state,v.winner))):''}${v.status==='cancelled'?'<p class="note">本轮已取消，没有获胜菜。投过的票和取消结果会保留。</p>':''}${v.status!=='active'&&!currentVote()?btn('发起新一轮','voteForm','secondary'):''}</div>${added?'<p class="note">每轮最多加入一次；即使这条菜单事项被取消，也不会重复加入。</p>':''}`;
}
function voteForm(){const f=ui.voteForm;return `${pagebar('发起投票')}<label class="field"><span>投票标题</span><input id="voteTitle" maxlength="50" value="${esc(f.title)}"></label><p class="subtitle mb">选择 2—10 道不同的菜 · 已选 ${f.dishIds.length} 道</p>${state.dishes.filter(d=>D.available(state,d.id)).map(d=>`<label class="checkbox-row"><input type="checkbox" data-vote-choice="${d.id}" ${f.dishIds.includes(d.id)?'checked':''}>${food(d)}<span>${esc(d.name)}</span></label>`).join('')}<div class="actions">${btn('发起投票','startVote','primary','',f.dishIds.length<2||f.dishIds.length>10)}</div>`;}
function profile(){const m=actor();return `${top()}<div class="profile-head">${avatar(m,true)}<div><h1>${esc(m?.name)}</h1><p class="subtitle">当前家庭成员</p></div></div>${btn('切换成员','identity','secondary')}<div class="card mt">${[['myOrders','我的点菜'],['myReviews','我的评价'],['manage','公共菜品管理'],['members','家庭成员'],['categories','菜品分类'],['settings','家庭与服务设置']].map(([a,l])=>`<button class="list-link" data-action="${a}"><span>${l}</span><span class="arrow">›</span></button>`).join('')}</div><p class="note">家庭菜品由大家共同管理，创建人不是私有菜品所有者。</p>`;}
function manage(){return `${pagebar('公共菜品管理')}<div class="row between mb"><p class="small muted">所有启用成员均可管理</p>${btn('＋ 新建菜品','dishForm','text-button')}</div><div class="stack">${state.dishes.map(d=>`<div class="card"><button class="row-open" data-action="dishForm" data-id="${d.id}" style="width:100%">${food(d)}<span class="dish-info"><b>${esc(d.name)}</b><small>${esc(state.categories.find(c=>c.id===d.categoryId)?.name)} · 第 ${d.revision} 版资料</small></span><span class="badge ${d.active?'pending':'cancelled'}">${d.active?'上架':'下架'}</span></button><div class="row between mt"><small class="muted">保留菜谱与历史</small>${btn(d.active?'下架':'上架','toggleDish','text-button',`data-id="${d.id}"`)}</div></div>`).join('')||empty('还没有菜品','新建第一道家庭菜谱吧。','dishForm','新建菜品')}</div>`;}
function dishForm(){const d=ui.edit;if(!d)return empty('表单未打开','请返回公共菜品管理。','manage','返回管理');return `${pagebar(d.id?'编辑公共菜品':'新建公共菜品')}<p class="small muted">这份资料由全家共享，保存时检查内容版本。</p><form id="dishForm"><label class="field"><span>菜名 *</span><input data-edit="name" maxlength="50" value="${esc(d.name)}" required></label><div class="split-actions"><label class="field grow"><span>分类 *</span><select data-edit="categoryId">${state.categories.filter(c=>c.active||c.id===d.categoryId).map(c=>`<option value="${c.id}" ${c.id===d.categoryId?'selected':''}>${esc(c.name)}${c.active?'':'（停用）'}</option>`).join('')}</select></label><label class="field grow"><span>预计时长（分钟）</span><input type="number" min="1" max="1440" data-edit="minutes" value="${esc(d.minutes??'')}" placeholder="选填"></label></div><label class="field"><span>简介</span><textarea rows="3" maxlength="1000" data-edit="intro">${esc(d.intro)}</textarea></label><div class="field"><span>封面原文件（选填）</span><div class="file-box"><label for="coverFile" class="secondary file-select">选择原文件</label><input id="coverFile" type="file" class="file-input" aria-label="选择封面原文件"><p>单文件上限 50 MiB。原文件可能含位置信息；原型仅作本机展示，不上传。</p>${d.cover?`<p><b>${esc(d.cover.name)}</b> · ${(d.cover.size/1048576).toFixed(2)} MiB</p>${fileURL&&d.cover.preview?`<img class="file-preview" src="${fileURL}" alt="本机文件预览" onerror="this.hidden=true">`:'<p>仅原文件信息 · 当前没有可用预览</p>'}${btn('移除封面','removeCover','text-button')}`:''}</div></div><div class="section-head"><h2>做法步骤</h2>${btn('＋ 添加一步','addStep','text-button')}</div><div class="stack">${d.steps.map((s,i)=>`<div class="card"><div class="row between"><span class="small">步骤 ${i+1}</span><span>${btn('上移','stepUp','text-button',`data-index="${i}"`,i===0)}　${btn('移除','removeStep','text-button',`data-index="${i}"`)}</span></div><textarea class="note-input" data-step="${i}" maxlength="2000" aria-label="步骤${i+1}" placeholder="写下这一步怎么做">${esc(s)}</textarea></div>`).join('')||'<p class="note">可以先保存菜品，以后再补充做法。</p>'}</div><div class="actions">${btn('保存菜品','saveDish','primary')}</div></form>`;}
function members(){return `${pagebar('家庭成员')}<p class="subtitle mb">所有启用成员均可管理；名称不限定家庭关系。</p>${btn('＋ 添加成员','newMember','secondary')}<div class="stack mt">${state.members.map(m=>`<div class="card"><div class="row">${avatar(m)}<div class="grow"><h3>${esc(m.name)}</h3><small class="muted">${m.id===ui.member?'当前成员 · ':''}${m.active?'启用':'停用'}</small></div>${btn('改名','editMember','text-button',`data-id="${m.id}"`)}</div><div class="row between mt"><small class="muted">历史记录长期保留</small>${btn(m.active?'停用':'启用','toggleMember','text-button',`data-id="${m.id}"`)}</div></div>`).join('')}</div>`;}
function categories(){return `${pagebar('菜品分类')}${btn('＋ 添加分类','newCategory','secondary')}<div class="card mt">${state.categories.map(c=>`<div class="list-link"><span><b>${esc(c.name)}</b><small style="display:block">${state.dishes.filter(d=>d.categoryId===c.id&&d.active).length} 道上架菜 · ${c.active?'启用':'停用'}</small></span><span class="review-tools">${btn('改名','editCategory','text-button',`data-id="${c.id}"`)}　${btn(c.active?'停用':'启用','toggleCategory','text-button',`data-id="${c.id}"`)}</span></div>`).join('')}</div>`;}
function settings(){return `${pagebar('家庭与服务设置')}<div class="card"><button class="list-link" data-action="editFamily"><span>家庭名称</span><small>${esc(state.family?.name)}　›</small></button><div class="list-link"><span>业务时区</span><small>北京时间 · ${esc(state.family?.timezone)}</small></div><div class="list-link"><span>家庭日期</span><small>${esc(state.today)}</small></div><button class="list-link" data-action="connect"><span>服务地址</span><small>查看与连接 ›</small></button></div><div class="note">家庭服务位于局域网。计划每日北京时间 04:00 停服备份，完成后恢复服务；期间请保留草稿，稍后重新连接。备份与恢复由维护人处理，本页面不提供运维操作。</div><div class="card mt"><h3>当前为交互演示</h3><p class="subtitle">页面使用浏览器本机数据，没有连接微信或后端服务。服务识别与数据代次只作模拟。</p><p class="small muted mt">实例：${esc(state.instance)}<br>代次：${esc(state.epoch)}</p></div>${btn('演示场景','showScenes','secondary','style="margin-top:20px"')}`;}
function identity(){return `<div class="topline"><small class="muted">${esc(state.family?.name||'家庭点菜')}</small>${btn('连接设置','connect','text-button')}</div><div class="identity-intro"><span class="eyebrow">MAKE YOURSELF AT HOME</span><h1 class="mt">今天，你是谁？</h1><p class="subtitle">选一位家庭成员，开始安排家常饭。</p></div><div class="stack">${state.members.filter(m=>m.active).map(m=>`<button class="identity-row" data-action="chooseMember" data-id="${m.id}">${avatar(m)}<span><b>${esc(m.name)}</b><small>${m.id===ui.member?'当前选择':'进入家庭菜单'}</small></span><span class="chevron">›</span></button>`).join('')||empty('没有可选成员','请联系家庭服务维护人检查数据。')}</div><p class="note" style="margin-top:28px">成员选择用于记录点菜与做菜的人，不是登录认证。仅供可信家庭局域网使用。</p><p class="demo-label">交互演示 · 示例日期 2026-09-10<br>首次使用流程可在“演示场景”中查看。</p>`;}
function connect(){return `${pagebar('连接家庭服务')}<div class="identity-intro"><h1>连上家里的厨房</h1><p class="subtitle">手机和 Linux 服务位于已允许的家庭网络内。</p></div><label class="field"><span>家庭服务地址</span><input id="serviceAddress" value="${esc(ui.address)}" placeholder="http://192.168.1.100:8080"><small class="help">示例地址，不会发送真实网络请求。</small></label>${btn('测试连接（演示）','testConnection','primary')}<p class="note">微信局域网请求、文件上传和原图显示需独立进行 iOS / Android 真机验证。浏览器可访问不等于小程序已通过发布验收。</p>`;}
function setup(){return `${pagebar('创建家庭')}<h1>给家常饭一个名字</h1><p class="subtitle">只在服务首次使用时设置。</p><label class="field"><span>家庭名称 *</span><input id="setupName" maxlength="30" value="幸福之家"></label><label class="field"><span>初始成员（每行一位）*</span><textarea id="setupMembers" rows="3">丈夫\n妻子</textarea></label><label class="field"><span>家庭业务时区</span><input id="setupTimezone" value="北京时间 · Asia/Shanghai" readonly aria-readonly="true"></label><p class="small muted">家庭日期统一按北京时间计算，无需手动选择时区。</p>${btn('创建并选择成员','setupSave','primary')}<p class="note">此处为一次性初始化流程演示。正式服务必须用事务保证并发初始化只能成功一次。</p>`;}
function overdue(){const xs=state.items.filter(i=>i.date<state.today&&['pending','cooking'].includes(i.status));return `${pagebar('往日未完成')}<p class="subtitle mb">接着做，或结束这一次。记录始终保留原日期。</p><div class="stack">${xs.map(menuCard).join('')||empty('都已经安排好了','当前没有往日未完成事项。','home','返回首页')}</div>`;}
function myOrders(){const xs=state.items.filter(i=>i.orderedBy===ui.member).sort((a,b)=>b.date.localeCompare(a.date));return `${pagebar('我的点菜')}<div class="stack">${xs.map(menuCard).join('')||empty('还没有点菜记录','选几道自己想吃的菜吧。','catalog','去点菜')}</div>`;}
function myReviews(){const rs=state.reviews.filter(r=>r.memberId===ui.member);return `${pagebar('我的评价')}<p class="subtitle mb">每天对同一道菜最多一条评价；提交后不能修改。</p><div class="stack">${rs.map(r=>{const i=menuItem(r.itemId);return `<div><button class="text-button" data-action="item" data-id="${i.id}">${esc(i.name)} · ${dateLabel(i.date)}　›</button>${reviewCard(r)}<p class="small muted">已提交</p></div>`;}).join('')||empty('还没有评价','完成一次做菜后，为家人的手艺留下评分。')}</div>`;}
function render(scroll=false){if(!state.family&& !['connect','setup'].includes(ui.page))ui.page='connect';if(!actor()?.active&&!['identity','connect','setup'].includes(ui.page)){ui.member=null;ui.page='identity';}const el=$('#screen'),old=el.scrollTop;let content='';const views={home,catalog,draft:draftView,dish:()=>dishView(ui.param),menu:()=>menu(ui.param||state.today),item:()=>itemView(ui.param),review:reviewView,history:historyView,repeat:()=>repeatView(ui.param),vote:()=>voteView(ui.param),voteForm,profile,manage,dishForm,members,categories,settings,identity,connect,setup,overdue,myOrders,myReviews};
 if(ui.loading)content=`${top()}<h1>正在读取家庭菜单</h1><div class="spinner"></div><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>${btn('结束加载演示','endLoading','secondary')}`;else content=(views[ui.page]||home)();el.innerHTML=headerBanner()+content;el.scrollTop=scroll?0:old;
 const tab={home:'home',menu:'home',item:'home',overdue:'home',vote:'home',voteForm:'home',review:'home',catalog:'catalog',dish:'catalog',draft:'catalog',history:'history',repeat:'history',profile:'profile',manage:'profile',dishForm:'profile',members:'profile',categories:'profile',settings:'profile',myOrders:'profile',myReviews:'profile'}[ui.page];$('#nav').hidden=!actor()||['identity','connect','setup'].includes(ui.page);$('#nav').style.display=$('#nav').hidden?'none':'';$('#nav').innerHTML=['home','catalog','history','profile'].map((p,i)=>`<button data-action="${p}" class="${tab===p?'active':''}" aria-label="${['首页','点菜','历史','我的'][i]}">${icon(p)}${['首页','点菜','历史','我的'][i]}</button>`).join('');document.querySelectorAll('.railnav button').forEach(b=>b.classList.toggle('active',b.dataset.action===ui.page));$('#scene').value=ui.scene;}
function sceneApply(name){if(['normal','empty','setup'].includes(name)){state=D.seed();ui=defaultUI();ui.scene=name;if(name==='empty'){state.items=[];state.reviews=[];state.votes=[];ui.member='m2';ui.page='home';}if(name==='setup'){state.family=null;state.members=[];state.items=[];state.reviews=[];state.dishes=[];state.votes=[];ui.page='connect';}}
 else{ui.scene=name;if(!ui.member){ui.member='m2';ui.page='home';}if(name==='offline')ui.offline=true;if(name==='loading')ui.loading=true;if(name==='unknown'){ui.nextUnknown=true;ui.page='catalog';}if(name==='conflict'){ui.nextConflict=true;ui.page='home';}if(name==='version'){ui.nextVersion=true;rawGo('dishForm','d1');}if(name==='epoch'){state.epoch='epoch-'+Date.now();ui.page='home';modal('家庭数据已重新载入','<p>这是恢复后数据代次变化的演示。旧缓存和待确认意图不会自动重送。请核对菜单，再重新选择。</p>');}}
 save();render(true);}
function requestScene(name){if(['normal','empty','setup'].includes(name))confirmAction('切换演示数据？','会替换当前浏览器中的演示菜单、草稿和评价，不影响任何真实服务。',()=>sceneApply(name),'切换演示',true);else{closeModal();sceneApply(name);toast('演示场景已启用');}}
function scenesDialog(){modal('演示场景',`<p>以下开关只属于原型，不是小程序产品设置。</p><div class="stack mt">${Array.from($('#scene').options).map(o=>btn(esc(o.text),'chooseScene','secondary',`data-scene="${o.value}"`)).join('')}</div>`);}
async function submit(){if(pending()){go('draft');return;}if(ui.offline){toast('当前离线，草稿已保留，未发送');return;}const items=draft();if(!items.length)return;const submitScope=scope();const intent={key:globalThis.crypto?.randomUUID?.()||'key-'+Date.now()+'-'+Math.random().toString(16).slice(2),instance:state.instance,epoch:state.epoch,member:ui.member,date:state.today,items:items.map(x=>({dishId:x.dishId,note:x.note,sourceItem:x.sourceItem||null}))};ui.pending[submitScope]=intent;ui.submitting=true;if(!save(true)){delete ui.pending[submitScope];ui.submitting=false;return;}render();await new Promise(r=>setTimeout(r,350));let res;
 try{res=D.execute(state,intent.member,'submit',intent);state=res.state;}catch(e){ui.submitting=false;delete ui.pending[submitScope];save();render();showError(e);return;}
 ui.submitting=false;if(ui.nextUnknown){ui.nextUnknown=false;save();render();toast('模拟：服务端已处理，但响应没有收到。请确认结果。');return;}delete ui.pending[submitScope];ui.drafts[submitScope]=[];save();if(scope()===submitScope){ui.menuFilter='all';rawGo('menu',res.result.date);}else render();toast('已加入家庭菜单，点菜人保持原成员');}
function reconcile(){const p=pending();if(!p)return;if(ui.offline){toast('请先恢复连接，原提交凭据仍保留');return;}try{const res=D.execute(state,p.member,'submit',p);state=res.state;delete ui.pending[scope()];ui.drafts[scope()]=[];save();ui.menuFilter='all';rawGo('menu',res.result.date);toast('已确认成功，没有重复加入');}catch(e){if(['DATE_CHANGED','MEMBER_INACTIVE','DISH_UNAVAILABLE'].includes(e.code)){delete ui.pending[scope()];save();render();}showError(e);}}
function submitName(type,id){const list=type==='Member'?state.members:state.categories,old=list.find(x=>x.id===id);modal(old?'编辑名称':'添加'+(type==='Member'?'成员':'分类'),`<label class="field"><span>名称</span><input id="entityName" maxlength="20" value="${esc(old?.name||'')}" placeholder="请输入名称"></label>`,[btn('保存','saveEntity','primary',`data-type="${type}" data-id="${id||''}"`)]);}
function editNote(id){const i=menuItem(id);modal('本次点菜备注',`<p>${esc(i.name)} · 只修改这一次的备注。</p><label class="field"><span>备注</span><textarea id="itemNote" maxlength="200" rows="3">${esc(i.note)}</textarea></label>`,[btn('保存备注','saveNote','primary',`data-id="${id}" data-revision="${i.revision}"`)]);}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;
 if(a==='confirmModal'){const fn=modalCallback;closeModal();fn?.();return;}if(a==='closeModal'){closeModal();return;}if(a==='back'){back();return;}
 if(a==='identity'){go('identity');return;}if(a==='chooseMember'){if(!state.members.find(m=>m.id===id)?.active){toast('该成员已停用');return;}ui.member=id;ui.stack=[];rawGo('home',null,false);return;}
 if(['home','catalog','history','profile','draft','manage','members','categories','settings','connect','overdue','myOrders','myReviews','voteForm'].includes(a)){closeModal();go(a);return;}
 if(['dish','item','review','dishForm','vote'].includes(a)){go(a,id||null);return;}
 if(a==='menu'){closeModal();ui.menuFilter=b.dataset.filter||'all';go('menu',b.dataset.date||state.today);return;}if(a==='repeat'){go('repeat',b.dataset.date);return;}
 if(a==='filterCategory'){ui.category=id;render();save();return;}if(a==='menuFilter'){ui.menuFilter=b.dataset.status;render();save();return;}
 if(a==='addDish'){addDish(id);return;}if(a==='removeDraft'){if(!pending()){ui.drafts[scope()]=draft().filter(x=>x.localId!==id);save();render();}return;}
 if(a==='submit'){await submit();return;}if(a==='reconcile'){reconcile();return;}
 if(a==='claim'){
  const i=menuItem(id),rev=i?.revision;if(!i)return;confirmAction('开始做这道菜？',`${actor()?.name} 将认领“${i.name}”。其他成员仍可查看做法。`,()=>{
   if(ui.nextConflict){ui.nextConflict=false;const other=state.members.find(m=>m.active&&m.id!==ui.member);try{state=D.execute(state,other.id,'claim',{id,revision:rev}).state;}catch(_){}save();render();modal('已被家人认领',`<p>${esc(menuItem(id).cookName)}已经开始做了。当前页面已显示最新状态，不会重复认领。</p>`,[btn('查看做菜记录','dependencyItem','primary',`data-id="${id}"`)]);return;}
   if(run('claim',{id,revision:rev})){rawGo('item',id);toast('已认领，开始做菜吧');}
  },'开始做');return;
 }
 if(a==='complete'||a==='unclaim'){const i=menuItem(id),rev=i.revision;confirmAction(a==='complete'?'确认这道菜已经做好？':'取消认领？',a==='complete'?'完成后家人可以评价。这条事项不能回到待做。':'这条事项将回到待做，其他家人可以接手。',()=>{if(run(a,{id,revision:rev})){render();toast(a==='complete'?'已完成，可以评价了':'已回到待做');}},a==='complete'?'确认做好了':'取消认领');return;}
 if(a==='cancelItem'){const i=menuItem(id);modal('这次不做了？','<p>取消本条点菜，保留记录，不影响同一道菜的其他事项。</p><label class="field"><span>原因（选填）</span><textarea id="cancelReason" rows="2" maxlength="200" placeholder="例如：今天临时不吃了"></textarea></label>',[btn('确认取消这一次','confirmCancel','danger',`data-id="${id}" data-revision="${i.revision}"`)]);return;}
 if(a==='confirmCancel'){const reason=$('#cancelReason').value,rev=Number(b.dataset.revision);closeModal();if(run('cancel',{id,revision:rev,reason})){render();toast('已取消并保留记录');}return;}
 if(a==='editNote'){editNote(id);return;}if(a==='saveNote'){const note=$('#itemNote').value;if(run('note',{id,note,revision:Number(b.dataset.revision)})){closeModal();render();toast('本次备注已保存');}return;}
 if(a==='rate'){ui.review.rating=Number(b.dataset.rating);ui.dirty=true;save();render();return;}if(a==='saveReview'){if(run('review',ui.review)){ui.dirty=false;rawGo('item',ui.review.id);toast('评价已保存');}return;}
 if(a==='repeatAdd'){if(pending()){go('draft');toast('请先确认上一次提交结果');return;}if(draft().length+ui.repeat.length>50){toast('一次最多 50 条，请减少所选');return;}for(const rid of ui.repeat){const i=menuItem(rid);if(!D.available(state,i.dishId)){toast('部分菜品不可点');return;}}for(const rid of ui.repeat){const i=menuItem(rid);draft().push({localId:'draft-'+Date.now()+'-'+rid,dishId:i.dishId,note:i.note,sourceItem:rid});}save();rawGo('draft');return;}
 if(a==='ballot'){const v=state.votes.find(v=>v.id===id),did=b.dataset.dish,current=v?.ballots[ui.member]||[],dishIds=current.includes(did)?current.filter(x=>x!==did):[...current,did];if(run('ballot',{id,dishIds})){render();toast(dishIds.includes(did)?'已选择，可继续多选':'已取消这道菜');}return;}
 if(a==='finishVote'){const v=state.votes.find(v=>v.id===id),top=D.leaders(v);if(top.length>1){modal('票数并列，选定一道菜',`<p>${Object.keys(v.ballots).length?'请从最高票的候选中选择。':'目前 0 票，所有候选并列。'}由发起人选定这一次的结果。</p>`,top.map(did=>btn(esc(v.candidates.find(c=>c.dishId===did).name),'selectWinner','primary',`data-id="${id}" data-dish="${did}"`)));}else confirmAction('结束本轮投票？','结束后不能继续投票或改票，结果会保留。',()=>{if(run('finishVote',{id})){render();toast('投票已结束');}},'结束投票');return;}
 if(a==='selectWinner'){if(run('finishVote',{id,winner:b.dataset.dish})){closeModal();render();toast('本轮结果已确定');}return;}
 if(a==='cancelVote'){confirmAction('取消本轮投票？','不产生获胜菜，取消结果仍然可以查看。',()=>{if(run('cancelVote',{id})){render();toast('本轮投票已取消');}},'确认取消',true);return;}
 if(a==='addWinner'){if(run('addWinner',{id,date:state.today})){render();toast('已加入今日菜单，每轮仅一次');}return;}
 if(a==='startVote'){const r=run('startVote',ui.voteForm);if(r){ui.dirty=false;rawGo('vote',r.id);toast('投票已发起');}return;}
 if(a==='toggleDish'){const d=dish(id),rev=d.revision;confirmAction(d.active?'下架这道菜？':'上架这道菜？',d.active?'下架后不能新点；菜谱、已点事项和历史仍保留。':'上架后家庭成员可以选择这道菜。',()=>{if(run('toggleDish',{id,revision:rev})){render();toast(d.active?'已下架':'已上架');}},d.active?'确认下架':'确认上架');return;}
 if(a==='addStep'){if(ui.edit.steps.length>=50){toast('最多 50 个步骤');return;}ui.edit.steps.push('');ui.dirty=true;save();render();return;}if(a==='removeStep'){ui.edit.steps.splice(Number(b.dataset.index),1);ui.dirty=true;save();render();return;}if(a==='stepUp'){const i=Number(b.dataset.index);[ui.edit.steps[i-1],ui.edit.steps[i]]=[ui.edit.steps[i],ui.edit.steps[i-1]];ui.dirty=true;save();render();return;}
 if(a==='removeCover'){ui.edit.cover=null;ui.dirty=true;if(fileURL){URL.revokeObjectURL(fileURL);fileURL=null;}save();render();return;}
 if(a==='saveDish'){if(ui.nextVersion&&ui.edit.id){ui.nextVersion=false;const d=dish(ui.edit.id);d.revision++;d.intro='家人刚刚保存了新的菜谱资料。';save();}const r=run('saveDish',ui.edit);if(r){ui.dirty=false;rawGo('dish',r.id);toast('公共菜品资料已保存');}return;}
 if(a==='inspectLatest'){closeModal();const d=dish(id);if(d)modal('当前资料 · 第 '+d.revision+' 版',`<h3>${esc(d.name)}</h3><p class="mt">${esc(d.intro)}</p><div class="card mt">${recipe(d)}</div><p class="small muted mt">你的未保存输入仍在表单里。可返回复制所需内容；重新打开编辑页会读取当前资料。</p>`);return;}
 if(a==='newMember'||a==='editMember'){submitName('Member',id);return;}if(a==='newCategory'||a==='editCategory'){submitName('Category',id);return;}if(a==='saveEntity'){const r=run('save'+b.dataset.type,{id:id||null,name:$('#entityName').value});if(r){closeModal();render();toast('名称已保存');}return;}
 if(a==='toggleMember'||a==='toggleCategory'){const isM=a==='toggleMember',x=(isM?state.members:state.categories).find(x=>x.id===id);confirmAction(x.active?'停用'+x.name+'？':'启用'+x.name+'？',x.active?'历史资料保留；如果有使用中的依赖，会显示具体原因。':'启用后可以继续参与家庭日常操作。',()=>{const r=run(a,{id});if(r){if(isM&&id===ui.member&&!r.active){ui.member=null;ui.page='identity';}save();render();toast(r.active?'已启用':'已停用');}},x.active?'确认停用':'确认启用');return;}
 if(a==='dependencyItem'||a==='dependencyVote'){closeModal();rawGo(a==='dependencyItem'?'item':'vote',id);return;}
 if(a==='editFamily'){modal('家庭名称',`<label class="field"><span>名称</span><input id="familyName" maxlength="30" value="${esc(state.family?.name)}"></label>`,[btn('保存','saveFamily','primary')]);return;}if(a==='saveFamily'){if(run('familyName',{name:$('#familyName').value})){closeModal();render();toast('家庭名称已保存');}return;}
 if(a==='testConnection'){const val=$('#serviceAddress').value.trim();try{const url=new URL(val);if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.search||url.hash)throw new Error();}catch(_){toast('请输入有效的 http:// 或 https:// 服务地址');return;}if(ui.offline){toast('连接不可达（离线演示），地址已保留');ui.address=val;save();return;}ui.address=val;save();confirmAction('连接成功（模拟）',state.family?`识别到“${state.family.name}”。本操作没有发送真实网络请求。`:'服务尚未初始化，请创建家庭。本操作没有发送真实网络请求。',()=>{ui.member=null;ui.stack=[];rawGo(state.family?'identity':'setup',null,false);},state.family?'选择成员':'创建家庭');return;}
 if(a==='setupSave'){const name=$('#setupName').value.trim(),names=$('#setupMembers').value.split('\n').map(x=>x.trim()).filter(Boolean);if(!name||[...name].length>30||!names.length||names.length>20||names.some(n=>[...n].length>20)||new Set(names.map(D.norm)).size!==names.length){toast('请填写家庭名与 1—20 位不同名称的成员');return;}if(state.family){toast('家庭已初始化');return;}state.family={name,timezone:'Asia/Shanghai'};state.members=names.map((name,i)=>({id:'member-init-'+i,name,active:true}));ui.stack=[];rawGo('identity',null,false);return;}
 if(a==='showScenes'){scenesDialog();return;}if(a==='applyScene'){requestScene($('#scene').value);return;}if(a==='chooseScene'){requestScene(b.dataset.scene);return;}if(a==='online'){ui.offline=false;save();render();toast('模拟连接已恢复，未自动提交任何内容');return;}if(a==='endLoading'){ui.loading=false;save();render();return;}
});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='search'){ui.search=t.value;const pos=t.selectionStart;save();render();$('#search')?.focus();$('#search')?.setSelectionRange(pos,pos);return;}if(t.dataset.draft){if(!pending()){const x=draft().find(x=>x.localId===t.dataset.draft);if(x)x.note=t.value;save();}return;}if(t.dataset.edit){ui.edit[t.dataset.edit]=t.value;ui.dirty=true;save();return;}if(t.dataset.step!==undefined){ui.edit.steps[Number(t.dataset.step)]=t.value;ui.dirty=true;save();return;}if(t.id==='reviewComment'){ui.review.comment=t.value;ui.dirty=true;save();return;}if(t.id==='voteTitle'){ui.voteForm.title=t.value;ui.dirty=true;save();return;}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.repeat){ui.repeat=t.checked?[...ui.repeat,t.dataset.repeat]:ui.repeat.filter(id=>id!==t.dataset.repeat);save();render();return;}if(t.dataset.voteChoice){ui.voteForm.dishIds=t.checked?[...ui.voteForm.dishIds,t.dataset.voteChoice]:ui.voteForm.dishIds.filter(id=>id!==t.dataset.voteChoice);ui.dirty=true;save();render();return;}if(t.id==='coverFile'){const f=t.files?.[0];if(!f)return;if(f.size>52428800||!f.size){toast(f.size?'文件超过 50 MiB，请选择较小的原文件':'空文件不能作为图片');t.value='';return;}if(fileURL)URL.revokeObjectURL(fileURL);const preview=['image/jpeg','image/png','image/webp','image/gif'].includes(f.type)&&f.size<=2097152;ui.edit.cover={name:f.name,size:f.size,type:f.type||'未知声明类型',preview};fileURL=preview?URL.createObjectURL(f):null;ui.dirty=true;save();render();toast('已选本机文件；实际内容识别与原图上传由正式服务执行');}});
$('#modal').addEventListener('close',()=>{if(!$('#modal').open)modalCallback=null;});
window.addEventListener('beforeunload',e=>{if(ui.dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(e.key!==KEY||!e.newValue)return;try{const x=JSON.parse(e.newValue);if(x.state?.version===2){state=x.state;render();}}catch(_){}});
// 测试工具仅用于原型的确定性演示，不供产品客户端调用。
window.__demo={reset:(scene='normal')=>{closeModal();state=D.seed();ui=defaultUI();sceneApply(scene);},state:()=>D.clone(state),ui:()=>D.clone(ui),route:(p,id)=>rawGo(p,id,false),actor:id=>{ui.member=id;save();render();},scenario:sceneApply,execute:(action,p,actorId)=>{const r=D.execute(state,actorId||ui.member,action,p);state=r.state;save();render();return r.result;}};
ui.submitting=false;render();

})();
